export const GENRES = [
    ['Action', 1],
    ['Adventure', 2],
    ['Cars', 3],
    ['Comedy', 4],
    ['Avante Garde', 5],
    ['Demons', 6],
    ['Mystery', 7],
    ['Drama', 8],
    ['Ecchi', 9],
    ['Fantasy', 10],
    ['Game', 11],
    ['Historical', 13],
    ['Horror', 14],
    ['Kids', 15],
    ['Martial Arts', 17],
    ['Mecha', 18],
    ['Music', 19],
    ['Parody', 20],
    ['Samurai', 21],
    ['Romance', 22],
    ['School', 23],
    ['Sci Fi', 24],
    ['Shoujo', 25],
    ['Girls Love', 26],
    ['Shounen', 27],
    ['Boys Love', 28],
    ['Space', 29],
    ['Sports', 30],
    ['Super Power', 31],
    ['Vampire', 32],
    ['Slice Of Life', 36],
    ['Supernatural', 37],
    ['Military', 38],
    ['Police', 39],
    ['Psychological', 40],
    ['Suspense', 41],
    ['Seinen', 42],
    ['Josei', 43],
    ['Award Winning', 46],
    ['Gourmet', 47],
    ['Work Life', 48],
];

export const RATED = [
    ['g', 'G - All Ages'],
    ['pg', 'PG - Children'],
    ['pg13', 'PG-13 - Teens 13 or older'],
    ['r17', 'R - 17+ recommended (violence & profanity)']
];

